# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-
lib = File.expand_path('../lib/', __FILE__)
$:.unshift lib unless $:.include?(lib)
 
require 'confluencer'

Gem::Specification.new do |s|
  s.name = %q{confluencer}
  s.version = Confluencer::VERSION
  s.platform    = Gem::Platform::RUBY
  s.required_rubygems_version = ">= 1.3.6"
  s.authors = ["Secret Sauce Partners, Inc."]
  s.date = %q{2010-06-02}
  s.description = %q{ActiveRecord-like classes to access Confluence through XMLRPC.}
  s.email = %q{github@secretsaucepartners.com}
  s.files = Dir.glob("{script,lib}/**/*") + %w(LICENSE README.rdoc VERSION)
  s.homepage = %q{http://github.com/sspinc/confluencer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Useful classes to manage Confluence.}
  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.7"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<log4r>, [">= 1.1.7"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<log4r>, [">= 1.1.7"])
  end
end
